### ISSUE TITLE
command line arguments

### ISSUE THREAD

**Issue by kserg9707** [Oldwayfarer/Image_to_ASCII#3]
Можно добавить больше аргументов вместо интерактивного режима. Для этого есть модули `getopt` или весьма простой и понятный `argparse`.
И вместо настроек после запуска можно передавать ключи. К примеру,
`./image_to_ASCII.py -m 2.0 -s 140 image.png`

**Comment by anfinogenov** [comment]
@kserg9707 Есть смысл оставить изучение модуля `getopt` до изучения Сишной `getopt()`, потому-что модуль `argparse`, по сути - стандарт получения информации от пользователя в программах на Python

**Comment by Oldwayfarer** [comment]
@anfinogenov добавил argparse

**Comment by anfinogenov** [comment]
@Oldwayfarer Хотелось бы иметь возможность использовать свой алфавит, например, иероглифы. То есть отдельный параметр, с помощью которого можно было бы загрузить Json словарь пар значений `{"диапазон": [множество символов]}`. По умолчанию используется текущий словарь

**Comment by kserg9707** [comment]
В argparse есть возможность делать ключи без параметра. Ключ `-s` принимает всего два значения, что может соответствовать наличию или отсутствию ключа.

**Comment by Oldwayfarer** [comment]
@kserg9707 Добавил Ключ -s без параметра

**Comment by Oldwayfarer** [comment]
@anfinogenov Добавил возможность использовать свой алфавит

**Comment by Oldwayfarer** [comment]
А, нет, есть косяки
