### ISSUE TITLE
GIFs

### ISSUE THREAD

**Issue by kserg9707** [Oldwayfarer/Image_to_ASCII#5]
Было бы интересно реализовать обработку анимаций (.gif) с возможностью задавать время между сменой кадров и количество повторений анимации.

**Comment by anfinogenov** [comment]
> повторений анимации

AFAIK гифки циклятся бесконечно

**Comment by kserg9707** [comment]
Чтобы не заспамить весь терминал и не использовать ctrl+c, можно добавить возможность ограничить кол-во отрисованных циклов. Или сделать выход из программы по нажатию клавиши.

**Comment by anfinogenov** [comment]
@kserg9707, то есть выводить гиф в консоль, а не файл? 
Если выводить в консоль, то надо `ncurses` подрубать, я думаю. Тогда и надобности в ограничении повторений не останется.

**Comment by kserg9707** [comment]
Можно выводить в консоль, кадры разделять с помощью `os.system('clear')`.
А в `ncurses` надо видео воспроизводить, но не все же сразу.

**Comment by anfinogenov** [comment]
> но не все же сразу

hold my beer

**Comment by anfinogenov** [comment]
> А в `ncurses` надо видео воспроизводить, но не все же сразу.

Предлагаю сразу делать красиво, чтобы потом не переделывать
[Тыц](https://docs.python.org/3/howto/curses.html)
