### ISSUE TITLE
Code rearrangement

### ISSUE THREAD

**Issue by anfinogenov** [Oldwayfarer/Image_to_ASCII#6]
https://github.com/Oldwayfarer/Image_to_ASCII/blob/a855a23af80fd73af9eaca3ba9482417b9162395/image_to_ASCII.py#L88-L152

В таких случаях рационально открыть файл с помощью `open()`, а затем закрыть его с `.close()`. Конструкция `with` порождает лишний уровень вложенности, сказывающийся на читаемости кода. Код стоит писать так, чтобы уровень вложенности не был выше 3. В 99% случаев это возможно без какого-либо изменения архитектуры приложения. Избавившись от конструкции `with` здесь, можно будет гораздо удобнее воспринимать обработку исключения:
```
try:
    image_file = Image.open(args.Image_name)
except FileNotFoundError: 
    print('file "{}" Doesn\'t exist'.format(args.Image_name)) 
except OSError: 
    print('can not identify image: "{}"'.format(args.Image_name)) 

# Код обработки изображения далее
```

**Comment by Oldwayfarer** [comment]
@anfinogenov То есть в любом месте в коде должно быть не более 3 уровней вложенности?

**Comment by anfinogenov** [comment]
@Oldwayfarer Если появляется сильная вложенность - это признак того, что пора выделять этот блок в отдельную функцию, либо существует решение проще.

Обращаясь к [PEP20](https://www.python.org/dev/peps/pep-0020/) (Python Zen):

> Beautiful is better than ugly.
> Simple is better than complex.
> Readability counts.
> If the implementation is hard to explain, it's a bad idea.
> If the implementation is easy to explain, it may be a good idea.
