### ISSUE TITLE
Fails after update

### ISSUE THREAD

**Issue by kserg9707** [Oldwayfarer/Image_to_ASCII#8]
После обновления до новой версии программа вылетает с ошибкой, если остается старый файл параметров. При этом некорректно закрывается `curses`, не возвращая терминал в обычный режим. Хотелось бы, чтобы при ошибке вызывалась какая-либо процедура, по-человечески закрывающая curses.

**Comment by anfinogenov** [comment]
> Хотелось бы, чтобы при ошибке вызывалась какая-либо процедура, по-человечески закрывающая curses.

Ведь она такая даже есть ;)

https://github.com/Oldwayfarer/Image_to_ASCII/blob/1c682d2154d4fcabbcd1e520f2e391803c81d9ea/image_to_ASCII.py#L27-L31

Я бы сделал обертку, объединяющую эту функцию и `exit()`, скажем, `exit_safe(exitcode)`, которая все аккуратненько закроет и завершит программу с кодом `exitcode`.

**Comment by Oldwayfarer** [comment]
@anfinogenov А если я, допустим, хочу чтобы по моему коду ошибки выводилось какое-то сообщение. Мне следует использовать словарь, где к коду сопоставляется описание? Или в питоне есть более аккуратные способы для этого?

**Comment by anfinogenov** [comment]
@Oldwayfarer В питоне обычно используется механизм обработки исключений: исключение как объект содержит в себе достаточно информации об ошибке. То, как сделано сейчас, со словарем, тоже имеет место быть. Эдакий C-way ;)

**Comment by Oldwayfarer** [comment]
@kserg9707 Исправил ошибку связанную с неверными сохранениями
